### ISSUE TITLE
I am getting this error while using it in React

### ISSUE THREAD

**Issue by chvasanthkumar** [IBM/aspera-connect-sdk-js#27]
Uncaught (in promise) Error: Could not start transfer: Error: startTransferPromise: No transfer method is available for starting a transfer
    at download (AsperaUpy.jsx:28:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at react-dom.development.js:9288:1

**Comment by dwosk** [comment]
Hi @chvasanthkumar, that usually means that Connect wasn't successfully initialized (via `initSession()`), and so there is no way to start the transfer (i.e. Connect status it not `RUNNING`). 

To see why Connect wasn't initialized, you can open up the Developer Tools in the browser, run `AW4.Logger.setLevel(2)`, and then refresh the page. There should be debug logs printed to console when Connect is initialized that will have more information.

**Comment by chvasanthkumar** [comment]
Hi Aspera Connect is connecting in initial render and able to download and Upload.

I am getting the above only after refreshing the page
