### ISSUE TITLE
getting error in React - No transfer method is available for starting a transfer

### ISSUE THREAD

**Issue by LKJREAL** [IBM/aspera-connect-sdk-js#32]
Dear dwosk,
May I get your advice or support?
..
Extension version 4.1.1
Aspera Connect version 4.2.2
..
My code in App.js in React

```
import './App.css';
import { Connect, Logger } from '@ibm-aspera/connect-sdk-js';

function testAspera() {
  // Logger.setLevel(2);
  const asperaWeb = new Connect();
  asperaWeb.initSession();

  const transferSpec = {
  paths: [
  {
  source: 'aspera-test-dir-large/100MB'
  }
  ],
  remote_host: 'demo.asperasoft.com',
  remote_user: 'aspera',
  remote_password: 'demoaspera',
  direction: 'receive'
  };

  asperaWeb.startTransfer(transferSpec);
}

function App() {

return (
<div className="App">
<input type="button" value={'test'} onClick={testAspera}/>
</div>
);
}

export default App;
```

----- Console Logs ---------
```
AW4.Logger.setLevel(2)
undefined
logger.js:72 [1] Request handler status changing from[undefined] to[INITIALIZING]
logger.js:72 Determining request strategy...
logger.js:72 Attempting extension strategy
logger.js:72 Checking if extension installed...
logger.js:72 Detecting Connect extension. Attempt 1
connect.js:1454 Uncaught Error: startTransfers: No transfer method is available for starting a transfer
    at Connect.startTransfers (connect.js:1454:1)
    at Connect.startTransfer (connect.js:1401:1)
    at testAspera (App.js:21:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
startTransfers @ connect.js:1454
startTransfer @ connect.js:1401
testAspera @ App.js:21
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(익명) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
react-dom.development.js:4161 [Violation] 'click' handler took 8924ms
connect.js:1454 Uncaught Error: startTransfers: No transfer method is available for starting a transfer
    at Connect.startTransfers (connect.js:1454:1)
    at Connect.startTransfer (connect.js:1401:1)
    at testAspera (App.js:21:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
startTransfers @ connect.js:1454
startTransfer @ connect.js:1401
testAspera @ App.js:21
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(익명) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
[Violation] 'click' handler took 20488ms
logger.js:72 Extension detected: {"type":"AsperaConnectCheckResponse","detail":{"extension_version":"4.1.1.1"}}
logger.js:72 Detecting Connect installation via extension. Attempt 1
logger.js:72 {request_id: 10500, min_version: '', method: 'GET', uri_reference: '/connect/info/version', body: ''}
logger.js:72 Native host impl received response: {"request_id":10500,"object_id":0,"frame_id":"63cc53e1-6d81-496e-b0c0-6cbcf4e5b352","status":200,"body64":"eyAic3lzdGVtX3dpZGUiIDogdHJ1ZSwgInZlcnNpb24iIDogIjQuMi4yLjEzNSIgfQ==","sender":{"id":"kpoecbkildamnnchnlgoboipnblgikpn","tab":{"id":1623070870},"url":"http://localhost:3000/","origin":"http://localhost:3000"},"complete":true,"name":"AsperaConnectResponse"}
logger.js:72 Detected Connect installation via extension.
logger.js:72 {request_id: 10000, min_version: '', method: 'GET', uri_reference: '/connect/info/version', body: ''}
logger.js:72 nmh init finished
logger.js:72 Connect initialized. Checking version now.
logger.js:72 {request_id: 10001, min_version: '', method: 'GET', uri_reference: '/connect/info/version', body: ''}
logger.js:72 Native host impl received response: {"request_id":10000,"object_id":0,"frame_id":"63cc53e1-6d81-496e-b0c0-6cbcf4e5b352","status":200,"body64":"eyAic3lzdGVtX3dpZGUiIDogdHJ1ZSwgInZlcnNpb24iIDogIjQuMi4yLjEzNSIgfQ==","sender":{"id":"kpoecbkildamnnchnlgoboipnblgikpn","tab":{"id":1623070870},"url":"http://localhost:3000/","origin":"http://localhost:3000"},"complete":true,"name":"AsperaConnectResponse"}
logger.js:72 [1] Request handler status changing from[INITIALIZING] to[RUNNING]
logger.js:72 Request queue empty.
logger.js:72 Resetting max activity outstanding.
logger.js:72 [1] Connect status changing from[INITIALIZING] to[RUNNING]
logger.js:72 Connect API is ready.
```
------------------------------------------------------

Thanks and best regards.
KJ.

**Comment by LKJREAL** [comment]
console screenshot with AW4.Logger.setLevel(2) in Console F12 dev mode in Chrome
![image](https://user-images.githubusercontent.com/111216349/194300550-f15bcbd3-a4c6-4575-8451-9452aeab55e2.png)

**Comment by dwosk** [comment]
Hi @LKJREAL, the error `startTransfers: No transfer method is available for starting a transfer` indicates that Connect is not yet `RUNNING` when the transfer is being initiated. When `initSession` is called, the SDK attempts to make a connection with the installed Connect client and will go through a sequence of status updates. Only when Connect is found and the status is marked as `RUNNING` will you be able to do transfers (as well as use most other SDK functions).

As you can see in the console logs (towards the bottom) there is a  line `Connect status changing from [INITIALIZING] to [RUNNING]`. Only after this point are you able to do transfers.

The problem you have is that you are calling `startTransfer` _immediately_ after calling `initSession`. Doing this will at best be a race condition and only work part of the time (if at all). You might be served adding a [status event listener](https://ibm.github.io/aspera-connect-sdk-js/AW4.Connect.html#addEventListener) and only allowing a call to `startTransfer` to happen if Connect is marked as `RUNNING`.

**Comment by LKJREAL** [comment]
Dear dwosk,
Thank you so much for your guide.
The below codes work fine.
------------------
import { Connect } from '@ibm-aspera/connect-sdk-js';

  const connect = new Connect();
  connect.initSession();


function testAspera() {

  const transferSpec = {
  paths: [
  {
  source: 'aspera-test-dir-large/100MB'
  }
  ],
  remote_host: 'demo.asperasoft.com',
  remote_user: 'aspera',
  remote_password: 'demoaspera',
  direction: 'receive'
  };

  var connectSpec = {
    "allow_dialogs" : true,
    "return_paths" : false,
    "return_files" : true,
    "use_absolute_destination_path" : false
  };

  var transferCallback = {
    success: function(result) {
      console.log('Start Aspera Transfer');
    },
    error: function(result) {
      console.log('Start Failed by Console message');
    }
  };

  connect.startTransferPromise(transferSpec, connectSpec, transferCallback);
}


function App() {

return (
<div className="App">

<input type="button" value={'Transfer   Test'} onClick={testAspera}/>

</div>
);
}

export default App;
