### ISSUE TITLE
What does the error message related to faspmanager-3.7.2.0.jar mean?

### ISSUE THREAD

**Issue by blogsook** [IBM/aspera-connect-sdk-js#69]
The following error message appears in faspmanager-3.7.2.0.jar in Aspera SDK 3.9.1.

ERROR SelectThread:160 - Error walking through messages with selection key: [sun.nio.ch.SelectionKeyImpl@55a20f94](mailto:sun.nio.ch.SelectionKeyImpl@55a20f94)
java.lang.IllegalArgumentException: Invalid UUID string: 4ed0d533-47c
        at java.util.UUID.fromString(UUID.java:194)
        at com.asperasoft.faspmanager.FaspMessage.getXferId(FaspMessage.java:651)
        at com.asperasoft.faspmanager.Session.processFasp2MgmtMessage(Session.java:749)
        at com.asperasoft.faspmanager.FileTransferSession.processFasp2MgmtMessage(FileTransferSession.java:374)
        at com.asperasoft.faspmanager.Session.processMgmtMessage(Session.java:807)
        at com.asperasoft.faspmanager.FileTransferSession.processMgmtMessage(FileTransferSession.java:516)
        at com.asperasoft.faspmanager.FaspManager.processMessage(FaspManager.java:510)
        at com.asperasoft.faspmanager.FaspManager.readKey(FaspManager.java:626)
        at com.asperasoft.faspmanager.FaspManager$FmManagementSelectHandler.selectRead(FaspManager.java:82)
        at com.asperasoft.faspmanager.util.SelectThread.walkThroughMessages(SelectThread.java:154)
        at com.asperasoft.faspmanager.util.SelectThread.run(SelectThread.java:119)

What does this error message mean?

**Comment by dwosk** [comment]
Hi @blogsook it looks like you are using the Java FASP Manager SDK, which is a totally different product/SDK. This repo is specific to the Connect SDK for Javascript. Unfortunately, I do not have any experience with the Java FASP Manager SDK so I suggest you open a ticket through the [IBM support portal](https://www.ibm.com/mysupport) so it can be routed to the appropriate team/SME.
